name: booking_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/Times-New-Roman.otf
    - family: SFProDisplay400
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF

    # - family: SFProDisplay400
    #   fonts:
    #     - asset: assets/fonts/SFPRODISPLAYMEDIUM.otf

    # - family: SFProDisplay500
    #   fonts:
    #     - asset: assets/fonts/SFPRODISPLAYSEMIBOLD.otf

    - family: SFProDisplay700
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.otf
    # - family: SFProDisplay700
    #   fonts:
    #     - asset: assets/fonts/SFPRODISPLAYHEAVY.otf